import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff8f2', paddingTop: 54 },
  centralizado: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff8f2' },
  titulo: { fontSize: 28, fontWeight: 'bold', color: '#7a2717', textAlign: 'center' },
  subtitulo: { fontSize: 15, color: '#77574f', textAlign: 'center', marginTop: 4, marginBottom: 8 },
  categoria: { fontSize: 20, fontWeight: 'bold', color: '#7a2717', marginTop: 18, marginBottom: 8 },
  lista: { paddingHorizontal: 16, paddingBottom: 24, flexGrow: 1 },
  card: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', padding: 14, borderRadius: 12, marginBottom: 10, borderWidth: 1, borderColor: '#f0d9cb' },
  cardConteudo: { flex: 1, paddingRight: 10 },
  itemNome: { fontSize: 16, fontWeight: 'bold', color: '#31221e' },
  itemDescricao: { fontSize: 13, color: '#77574f', marginTop: 3, lineHeight: 18 },
  itemPreco: { fontSize: 15, fontWeight: 'bold', color: '#b23a20', marginTop: 7 },
  controleQuantidade: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  botaoQuantidade: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#b23a20', alignItems: 'center', justifyContent: 'center' },
  botaoQuantidadeTexto: { color: '#fff', fontSize: 20, fontWeight: 'bold', lineHeight: 23 },
  quantidade: { minWidth: 20, textAlign: 'center', fontSize: 16, fontWeight: 'bold', color: '#31221e' },
  vazio: { textAlign: 'center', color: '#8d6e63', fontSize: 16, marginTop: 80 },
  rodape: { backgroundColor: '#fff', padding: 16, borderTopWidth: 1, borderTopColor: '#f0d9cb' },
  total: { fontSize: 21, fontWeight: 'bold', color: '#7a2717', textAlign: 'right', marginBottom: 12 },
  botaoPrimario: { backgroundColor: '#b23a20', padding: 15, borderRadius: 10, alignItems: 'center' },
  botaoPrimarioTexto: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  botaoSecundario: { borderWidth: 1, borderColor: '#b23a20', padding: 13, borderRadius: 10, alignItems: 'center', marginTop: 10 },
  botaoSecundarioTexto: { color: '#b23a20', fontSize: 15, fontWeight: '600' },
  resumoLinha: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#fff', padding: 14, borderBottomWidth: 1, borderBottomColor: '#f0d9cb' },
  resumoItem: { flex: 1, color: '#31221e', fontSize: 15, paddingRight: 10 },
  resumoValor: { color: '#7a2717', fontWeight: 'bold' },
  pedidoCard: { backgroundColor: '#fff', padding: 16, borderRadius: 12, marginTop: 12, borderWidth: 1, borderColor: '#f0d9cb' },
  pedidoData: { fontSize: 13, color: '#8d6e63', marginBottom: 8 },
  pedidoItem: { fontSize: 14, color: '#31221e', marginTop: 3 },
  erro: { backgroundColor: '#ffebee', color: '#b71c1c', padding: 10, marginHorizontal: 16, marginTop: 8, borderRadius: 8, textAlign: 'center' },
  formulario: { flexGrow: 1, justifyContent: 'center', paddingHorizontal: 24, paddingBottom: 40 },
  campoGrupo: { marginTop: 16 },
  campoRotulo: { color: '#31221e', fontSize: 15, fontWeight: '600', marginBottom: 6 },
  campo: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e4c9bb', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, color: '#31221e' },
  botaoDesabilitado: { opacity: 0.6 },
})
